# Generated by Django 2.1.3 on 2018-11-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181113_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='img_big',
        ),
        migrations.AddField(
            model_name='post',
            name='img_small',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
